const Seo = () => {
  return (
    <>
      <title>Jeong Hoon Jo | Portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
};

export default Seo;
